"""add resume_id to interview sessions

Revision ID: 794e8399aca0
Revises: 032c63d8db72
Create Date: 2026-05-15 09:08:48.149545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794e8399aca0'
down_revision: Union[str, Sequence[str], None] = '032c63d8db72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('resume_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'interview_sessions', 'resumes', ['resume_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.drop_column('interview_sessions', 'resume_id')
    # ### end Alembic commands ###
