name: CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:

  backend-docker-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Backend Docker Image
        run: |
          docker build \
            -t interview-backend \
            ./Interview-Platform-Backend

  frontend-docker-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Frontend Docker Image
        run: |
          docker build \
            -t interview-frontend \
            ./Interview-Platform-Frontend